# Generated by Django 4.0.2 on 2022-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('ssn', models.PositiveBigIntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default='medrecsite@bme.com', max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('city', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=50)),
                ('height', models.IntegerField(max_length=3)),
                ('weight', models.IntegerField(max_length=3)),
                ('date_of_birth', models.DateField()),
                ('diatype', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
            ],
        ),
    ]
