# Generated by Django 4.0.2 on 2022-02-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientid',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientid',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
