# Generated by Django 4.0.2 on 2022-02-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_patientid_height_alter_patientid_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientid',
            options={'ordering': ['ssn']},
        ),
    ]
