# Generated by Django 4.0.2 on 2022-02-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_patientid_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientid',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='patientid',
            name='age',
            field=models.CharField(default=30, max_length=50),
        ),
        migrations.AlterField(
            model_name='patientid',
            name='diatype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientid',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientid',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientid',
            name='ssn',
            field=models.CharField(max_length=50),
        ),
    ]
