# Generated by Django 4.0.2 on 2022-03-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_info_patientrecord_delete_patientinfo'),
        ('pages', '0004_remove_patientid_date_of_birth_patientid_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patientID',
        ),
    ]
