# Generated by Django 4.0.2 on 2022-02-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_alter_patientid_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.patientid')),
            ],
            options={
                'ordering': ['ssn'],
            },
        ),
    ]
