# Generated by Django 4.0.2 on 2022-03-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('bmi', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_city',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_diatype',
            field=models.CharField(blank=True, choices=[('type1', 'type1'), ('type2', 'type2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_ssn',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='p_weight',
            field=models.IntegerField(),
        ),
    ]
