# Generated by Django 4.0.2 on 2022-03-04 20:00

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_delete_readings'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('ssn', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default='medrecsite@bme.com', max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('diatype', models.CharField(blank=True, choices=[('type1', 'type1'), ('type2', 'type2')], max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
            ],
            options={
                'ordering': ['ssn'],
            },
        ),
        migrations.CreateModel(
            name='patientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=datetime.datetime), size=None), size=None)),
                ('ssn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient_info')),
            ],
            options={
                'ordering': ['ssn'],
            },
        ),
        migrations.DeleteModel(
            name='patientInfo',
        ),
    ]
