# Generated by Django 4.0.2 on 2022-03-05 11:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_info_patientrecord_delete_patientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='glucose',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
    ]
