# Generated by Django 4.0.2 on 2022-03-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_fname', models.CharField(max_length=50)),
                ('D_lname', models.CharField(max_length=50)),
                ('D_ssn', models.CharField(max_length=50, unique=True)),
                ('D_password', models.CharField(max_length=50)),
                ('D_email', models.EmailField(default='medrecsite@bme.com', max_length=254)),
                ('D_phone', models.CharField(max_length=50)),
                ('D_city', models.CharField(max_length=70)),
            ],
        ),
    ]
